# Generated by Django 2.2 on 2019-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete='CASCADE', to='sales.User')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete='CASCADE', to='sales.SellOrder')),
            ],
            options={
                'db_table': 'sell',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('goods', models.ForeignKey(on_delete='CASCADE', to='sales.Goods')),
            ],
            options={
                'db_table': 'reserve',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete='CASCADE', to='sales.User')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete='CASCADE', to='sales.PurchaseOrder')),
            ],
            options={
                'db_table': 'Purchase',
            },
        ),
    ]
